- docs/docs.md
- src/api.ts
```
Franklin Harding [9:05 PM]
I don't like the stars route
Caleb Eby [9:05 PM]
Oh?
Franklin Harding [9:05 PM]
It's just a part of the user resource
It should be on `/users` and `/users/{id}`
Caleb Eby [9:06 PM]
Can the frontend get the current user ID via the jwt?
Franklin Harding [9:06 PM]
Yes!
Caleb Eby [9:06 PM]
Without making a request
Franklin Harding [9:06 PM]
Yes!
Caleb Eby [9:06 PM]
Yes!
Franklin Harding [9:06 PM]
Because JWT rules
Caleb Eby [9:06 PM]
Ok docs PR, sgtm
```
> Add stars to user resource and remove stars route

- index.html
- package-lock.json
- package.json
- postcss.config.js
- rollup-index.html
Now we have `font-display: swap`, so before the Google fonts have loaded, it uses a different font instead.
https://deploy-preview-149--peregrine.netlify.com
> Inline Google Fonts CSS

- src/components/match-card/index.tsx
- src/utils/format-time/index.test.ts
- src/utils/format-time/index.ts
Before: https://dev.peregrine.ga/events/2018pncmp
After: https://perf-faster-date-formatting--peregrine.netlify.com/events/2018pncmp
After it switches tabs much faster, you can test it
> Faster date formatting

- src/utils/compare-events/index.ts
This fixes a bug I was seeing where on the first render it used the cached events, and then once it got the events from network it sorted them slightly differently (only for events with the same date). This fixes that
> Make event sorting deterministic

- src/routes/event-analysis.tsx
(This change is only visible on screens that are wider than the # of columns)
[The space on the right is bad](https://dev.peregrine.ga/events/2019orwil/analysis):
[I fixed it](https://fix-analysis-table-wide-screens--peregrine.netlify.com/events/2019orwil/analysis):
> Fix analysis table for very wide screens

- src/sw.ts
There was an error, saying that it wanted the same origin header. So I added it now there is no error
https://fix-sw-console-error--peregrine.netlify.com/
> Fix sw console error

- package.json
- src/api/event-info/get-events.ts
- src/cache/events.ts
- src/cache/index.ts
- src/cache/matches.ts
- src/utils/empty-promise.ts
- src/utils/idb-promise.ts
- src/utils/prevent-empty-arr-resolve.ts
- src/utils/prevent-undefined-resolve.ts
Previously events that existed on TBA that were then deleted from TBA were sticking around in the indexeddb cache
> Fix event deletion from cache

- .gitignore
- package-lock.json
- package.json
- rollup.config.js
- src/api/event-info/index.ts
- src/components/event-info-card.tsx
- src/routes/home.tsx
- src/utils/compare-events/index.test.ts
- src/utils/compare-events/index.ts
- src/utils/distance-between-coordinates.ts
- src/utils/empty-promise.ts
- src/utils/use-geo-location.ts
- types.d.ts
- webpack.config.js
https://improve-event-sorting--peregrine.netlify.com/
Now it sorts them good:
1. *Current Events* - Sorted by proximity, then by name
2. *Future Events* - Sorted by soonest upcoming first
3. *Past Events* - Sorted by most recent first
It also now works correctly for the last day of the event, it still shows them as active until the end of the endDate (even though the endDate timestamp is the very beginning of the day)
It also works correctly with event timezones, it preserves the date into the current timezone, which fixes problems with the event day being off by one
> Improve event sorting

- src/routes/event-team.tsx
Now when you click on the link from a comment on a team that goes to the match, the link works, instead of not
Closes #540
> Fix matches link

- src/api/event-info/index.ts
- src/components/event-info-card.tsx
We are currently plugging event lat/lon directly into Google Maps, this doesn't show the name or details of the event space. TBA provides full Google Maps URLs for events, using this instead is a bit nicer.
> Use gmapsUrl from TBA rather than lat/lon directly

- src/components/event-card/index.tsx
- src/routes/home.tsx
https://style-event-filtering--peregrine.netlify.com/
I added CSS for the event filtering. This PR is targeting the `event-filtering` branch. Then I'll merge it to `dev`.
I made the home page only display the first 20 events after sorting. This prevents (or reduces) typing lag when searching on low-perf devices.
> Style event filtering

- src/api/event-info/get-events.ts
Reverts Pigmice2733/peregrine-frontend#732
Because currently `dev` is showing events from all years (so if you search for wilsonville, it shows 2 wilsonvilles, without telling you which is which).
We will be implementing the ability to filter by year in the BE, and then a follow up PR will be implemented here to add a `year` dropdown
> Revert "Get events from all years from the BE (#732)"

- .babelrc.js
- package-lock.json
- package.json
- src/api/base.ts
- src/api/event-info/get-events.ts
- src/api/get-years.ts
- src/api/match-info/get-event-matches.ts
- src/app.tsx
- src/cache/events/get-cached.ts
- src/components/authenticated/index.test.tsx
- src/components/chart.tsx
- src/components/dropdown.tsx
- src/router.tsx
- src/routes/home.tsx
- src/url-manager.ts
- src/utils/cancellable-promise/index.test.ts
- src/utils/cancellable-promise/index.ts
- src/utils/fastest-promise/index.ts
- src/utils/use-network-cache.ts
- src/utils/use-promise/index.tsx
- src/utils/use-query-state.ts
- types/index.d.ts
https://event-year-filtering--peregrine.netlify.com/
This is a big change. I fixed/improved some things tangentially related to the dropdown I added
---
I created a `CancellablePromise` which took forever. It allows cancelling from anywhere in the promise chain, and cancellations bubble all the way up to the original promise.
Because of that, now HTTP requests get canceled when the requirements change before the response comes back. For example, using the year dropdown, if you switch back and forth very fast, it will cancel requests that didn't finish before the dropdown was switched. Before this change, this would happen on slow networks:
- Filter = 2019
- Retrieve + display 2019 events from cache
- Start request for 2019 events
- Filter changed to 2020
- Retrieve + display 2020 events …
> Add event year filtering

- src/components/analysis-table.tsx
- src/components/chart.tsx
- src/components/dropdown.tsx
- src/components/field-card.tsx
- src/utils/clean-field-name.ts
Now the chart dropdown has the fields grouped into auto and teleop
Also, across the whole app, ` (auto)` and ` (teleop)` is removed from the end of the field names. This is temporary because those were only there for a workaround. When we support auto + teleop fields having the same name, this can be removed
Also, this fixes a bug where the chart dropdown was not auto-selecting the first field correctly. It was trying to select a hidden field, because the first field in this year's schema is hidden
https://default-chart-dropdown--peregrine.netlify.com/events/2020week0/teams/4041
Compare to this which is bad (what is the chart even showing?????)
https://peregrine.ga/events/2020week0/teams/4041
Before:
After:
> Improvements to chart dropdown

- src/components/analysis-table.tsx
- src/components/table.tsx
Bug: duplicate table column names don't click right: https://peregrine.ga/events/2020week0/analysis
Fix: https://fix-table-columns--peregrine.netlify.com/events/2020week0/analysis
> Fix table columns keys with same names

- src/routes/event-team-comments.tsx
Before: 
After:
- Fixed alignment for multiple comments
- Added link to match
https://improve-team-comments-page--peregrine.netlify.com/events/2020week0/teams/4905/comments
> Fix alignment for multiple comments + add link

- src/components/dropdown.tsx
- src/routes/signup.tsx
http://dont-default-realm-to-pigmice--peregrine.netlify.com/signup
Now the realm dropdown defaults to empty and it won't let you sign up until you select one
So now hopefully people don't keep accidentally signing up for pigmice (~20 people have)
> Don't default realm to pigmice

- src/components/event-matches.tsx
http://good-match-filtering-sorting--peregrine.netlify.com/events/2019micmp1
This is a good event for a test case, because
- It has a lot of matches
- It has teams 27, 67, and 2767
1. Search for 67
- Qual 67 should show up first. The match key matches the query exactly. Same if you searched for `qm67` or `qUaL 67`
- Next is all the matches that include team "67", sorted chronologically
- Next is all the matches that include teams whose numbers include "67" - so all of 2767's and 5567's and 5676's matches, sorted chronologically
2. Search for 27
3. Search for 67
4. Search for "quarters"
5. Search for "quarters 3"
http://good-match-filtering-sorting--peregrine.netlify.com/events/2019cadm
This is a good event for a test case, because
- It has team 8
1. Search for 8
- First should be Qual 8, …
> Implement good match sorting+filtering

- src/components/event-matches.tsx
- src/components/match-card.tsx
- src/routes/event-match.tsx
- src/routes/event-team.tsx
- src/routes/event.tsx
https://link-from-match-card-to-teams--peregrine.netlify.com/events/2020isde1/matches/qm1
When you are on a match page
The "match card" now links each team to that team's page
This does not apply to match cards that are themselves links (anywhere else on the site)
> Add teams links to match card

- src/components/analysis-table.tsx
- src/components/chart.tsx
- src/components/table.tsx
- src/routes/event-analysis.tsx
- src/routes/event-match.tsx
- src/url-manager.ts
- src/utils/encode-qs.ts
- src/utils/get-field-key.ts
- src/utils/urls/event-team.ts
https://preserve-sort-column--peregrine.netlify.com/events/2020week0/analysis
When you are on the analysis table
When you sort by a column other than team
And you tap on the link to that team
The graphs on the team page should default to the stat you were sorting by
Same for when you are on the mini-analysis-table on the event-match page
> Preserve sort column

- src/components/chart.tsx
https://fix-graphs-matching--peregrine.netlify.com/events/2020orore/analysis
Sort by different columns (including columns duplicated between auto and teleop) and go to teams, make sure that it is not getting the auto stat for the teleop stat, and reverse of that. Also make sure that field names without "auto" or "teleop" are working correctly
> Fix graphs matching field keys

- src/components/match-card.tsx
I was seeing this weird layout for the match cards specifically on the match page on my phone:
Now it is fixed
https://fix-wonky-match-cards--peregrine.netlify.com/events/2020wasno/matches/qm1
> Fix wonky match cards

- src/components/table.tsx
https://fix-reverse-sort--peregrine.netlify.com/events/2020orore/analysis
The bug was introduced in #808
> Fix reverse sort

- src/components/analysis-table.tsx
This PR fixes the bug. #822 also fixes the bug. If #822 works on iOS, I'd like to merge both fixes. If #822 doesn't work on iOS, only this fix should be merged
---
https://peregrine.ga/events/2020orore/matches/qm2
On small screens, there is a double border on the bottom of the cells in the rank column
This fixes that
https://fix-double-border-alt--peregrine.netlify.com/events/2020orore/matches/qm2
Verify:
- Double border is no longer shown on the match analysis
- All tables across the site have the correct borders, even when scrolling (Analysis Table, Users Table)
> Remove double underline: Alternate fix

- src/routes.ts
- src/routes/event-team-matches.tsx
- src/routes/event-team.tsx
https://event-team-matches-route--peregrine.netlify.com/events/2020orore/teams/2411
Click "View Matches"
Make sure match searching only applies to matches that include that team. So if you search for another team it should show matches that both teams are in
> Add event team matches route

- src/routes/event-team.tsx
Dev/Prod:
https://dev.peregrine.ga/events/2020waspo/teams/2147
- Ugly 404 bar
- Ugly Ranking Points is right up against edge
This branch:
https://handle-team-404--peregrine.netlify.com/events/2020waspo/teams/2147
- ? is a lot nicer
- No 404 bar because error is caught
> Ignore error if team info endpoint returns 404

- src/routes/home.tsx
- src/utils/use-geo-location.ts
Closes #890
https://add-geolocation-button--peregrine.netlify.app/
- There should be no geolocation prompt until you click the geolocation button on the homepage
- The geolocation button should not appear if you already clicked "allow" or "block"
- When you click on the geolocation button the browser should prompt for your location
In iOS and safari, we don't have the ability to know if the user has clicked "allow" or "block" so the button will always appear.
> Add geolocation button

- .babelrc.output.js
- package.json
For some reason really old versions of android browser started getting
included in our browserslist. I don't know why.
This caused many extra transforms to be enabled, including the
regenerator transform which broke the whole site.
I manually force-disabled those bad transforms, and I also manually
disabled support for really old versions of android browser (2014)
> Fix browserslist

- src/api/realm/get-realms.ts
- src/routes/signup.tsx
closes #1548 
Title says it all.
> sort realms alphabetically in dropdown on signup page

- src/routes/home.tsx
- src/routes/leaderboard.tsx
On the home and leaderboard pages, the year dropdown should default to the current year rather than the last year with events.
> default to the current year in year dropdowns
