Pigmice2733/peregrine-frontend

- docs/docs.md
- src/api.ts
> Add create event and create match to api

- docs/docs.md
- src/api.ts
- src/components/match-card/index.tsx
- src/components/match-card/style.css
- src/index.tsx
- src/routes/event-match/index.tsx
- src/routes/event/index.tsx
Closes #103 
https://add-match-page--peregrine.netlify.com/events/2018orwil - click on a match
> Add match page

- src/components/page/style.css
https://fix-arrow-alignment--peregrine.netlify.com/events/2018glbbb
> Fix header icon alignment

- src/components/spinner/index.tsx
- src/components/spinner/style.css
- src/index.tsx
- src/routes/event-match/index.tsx
- src/routes/event/index.tsx
- src/routes/home/index.tsx
We added a spinner for the default page loader and for each individual page
> Add spinner

- build.js
- docs/docs.md
- jest.setup.ts
- package-lock.json
- postcss.config.js
- src/api/event-info/index.ts
- src/api/report/index.ts
- src/api/schema/index.ts
- src/components/authenticated/index.test.tsx
- src/components/button/style.css
- src/components/card/style.css
- src/components/enum-selector/index.tsx
- src/components/enum-selector/style.css
- src/components/field-card/index.tsx
- src/components/field-card/style.css
- src/components/number-input/index.tsx
- src/components/number-input/style.css
- src/components/team-picker/index.tsx
- src/components/team-picker/style.css
- src/components/text-input/index.tsx
- src/components/text-input/style.css
- src/routes/scout/index.test.tsx
- src/routes/scout/index.tsx
- src/routes/scout/style.css
- src/utils/format-title/index.test.ts
- src/utils/format-title/index.ts
> Scout page!

- docs/docs.md
- src/api/report/get-event-team-auto-stats.ts
- src/api/report/get-event-team-stats.ts
- src/api/report/get-event-team-teleop-stats.ts
- src/api/report/get-team-auto-stats.ts
- src/api/report/get-team-stats.ts
- src/api/report/get-team-teleop-stats.ts
- src/api/report/index.ts
cuz why not
and frank said so
and why were they separate in the first place
> Merge analysis endpoints

- package-lock.json
- package.json
- postcss.config.js
- rollup.config.js
- src/api/report/get-event-stats.ts
- src/api/report/index.ts
- src/components/analysis-table/index.tsx
- src/components/analysis-table/style.css
- src/components/icon-button/style.css
- src/components/icon/style.css
- src/components/page/style.css
- src/load-data/index.tsx
- src/routes/event/index.tsx
- src/routes/event/style.css
- src/type-utils.ts
- src/utils/compare-teams/index.test.ts
- src/utils/compare-teams/index.ts
- src/utils/format-percent/index.test.ts
- src/utils/format-percent/index.ts
- types.d.ts
https://analysis-table--peregrine.netlify.com/events/2018cc
> Add analysis table

- src/components/analysis-table/index.tsx
- src/components/match-card/index.tsx
- src/components/match-card/style.css
Before:
https://dev.peregrine.ga/events/2018pncmp
After:
https://reduce-dom-nodes--peregrine.netlify.com/events/2018pncmp
> Reduce dom nodes

- .github/main.workflow
- .github/workflows/continuous-integration-workflow.yml
> GitHub actions

- src/components/dropdown.tsx
http://fix-register-page--peregrine.netlify.com/register
No longer hangs on load.
Closes #542
> Fix register page

- src/colors.ts
- src/components/analysis-table.tsx
- src/components/chart.tsx
- src/components/table.tsx
- src/components/toggle/index.tsx
> Add stat rank position to analysis table

- CODE_OF_CONDUCT.md
- src/routes/home.tsx
Adds `CODE_OF_CONDUCT.md` and a link to Netlify at the bottom of the home page.
Because we are running out of build minutes (300/month on the free plan) and I want to switch to the open source plan which has 1000/month
> Add stuff so that we can use the netlify open source plan

- src/components/comment-card.tsx
- src/routes/event-team-comments.tsx
- src/utils/use-promise/index.tsx
https://dont-wait-for-reporter-to-load--peregrine.netlify.com/events/2019cc/teams/4183
> Don't wait for reporter to load before displaying comments

- package-lock.json
- package.json
- src/api/match-info/index.ts
- src/components/card/index.tsx
- src/components/video-card.tsx
- src/routes/event-match.tsx
- src/utils/clean-youtube-url/index.ts
- src/utils/clean-youtube-url/test.ts
- src/utils/use-network-connection.ts
https://match-videos--peregrine.netlify.com/events/2020week0/matches/qm14
https://match-videos--peregrine.netlify.com/events/2019cc/matches/qm10
- Resize your browser really small
- Go to devtools network tab and emulate offline. The video player should go away instantly
- Go to devtools network tab and emulate a 3g or slower network. If you reload the page, the video player should not load until you click on the black box (conditional lazy loading)
> Match videos

- package.json
- src/components/dropdown.tsx
- src/routes/signup.tsx
- Force user to select a realm when registering (#801)
> Dev -> master

- src/routes/signup.tsx
https://fix-realm-dropdown--peregrine.netlify.com/signup
before when you choose a team from the dropdown it would choose a different team for you
thats not what you wanted
now when you choose a team from the dropdown, it selects the one you chose :tada:
> Fix realm dropdown

- rollup.config.js
Fixes:
https://github.com/egoist/rollup-plugin-postcss/pull/262#issuecomment-616773040
> Fix breaking change in rollup-plugin-postcss

- src/components/report-viewer.tsx
- src/routes/home.tsx
> Main page all events

- src/components/video-card.tsx
- src/routes/event-match.tsx
- src/utils/use-network-connection.ts
> loading match pages offline

- src/routes/event-team.tsx
This should be merged as a non-squash merge. "Create a merge commit"
> Merge dev -> main

- package-lock.json
- package.json
- src/components/heading.tsx
- src/utils/memo.ts
- src/utils/mock-fetch.ts
- src/utils/request-idle-callback.ts
Co-authored-by: Elijah Vennebush <ev118@users.noreply.github.com>
Co-authored-by: Alex <avhoi83@gmail.com>
> Update TS and fix type errors

- src/api/report/submit-report.ts
- src/components/report-editor.tsx
> created an alert when local reports are uploaded
